### ISSUE TITLE
No extension is showing up when using Verdaccio on localhost

### ISSUE THREAD

**Issue by jfthuong** [joelspadin-garmin/vscode-private-extension-manager#13]
Hi,

I have found your extension on the [Private Repo Feature Request](https://github.com/Microsoft/vscode/issues/21839) and it sounds awesome.

I'm new to npm package publication (and extension publication for what matters) so it is possible I have not done the right things.

What I have done:

1. Install Vercaccio
2. Add a user in Verdaccio
3. Run Verdaccio locally (http://localhost:4873)
4. Modify my **package.json** to contain the information you specified (see below)
5. Run `npm publish .` => it worked and we can see the package in Verdaccio webpage
6. Install your extension in VS Code
7. Set up the repository (http://localhost:4873) in either the Workspace OR user settings
8. Click on **Refresh**  => Nothing happens.

This is an extract of **package.json**
```json
"icon": "assets/logo.png",
"files": [
        "my-extension.vsix",
        "assets/logo.png"
    ],
    "scripts": {
        "prepublishOnly": "vsce package -o my-extension.vsix"
    },
    "publishConfig": {
        "registry": "http://localhost:4873"
    },
    "repository": {
        "type": "git",
        "url": "git@... git repo"
    },
    "version": "0.3.2",
    "preview": true,
    "engines": {
        "vscode": "^1.44.0"
    },
    "galleryBanner": {
        "color": "#000000",
        "theme": "dark"
    },
    "categories": [
        "Themes"
    ],
    "keywords": [
        "color",
        "theme"
    ],
    "devDependencies": {
        "vsce": "^1.75.0"
    },
```

And **settings.json** (for user)
```json
    "privateExtensions.registries": [
        {
            "name": "VS Code Extensions for private use",
            "registry": "http://localhost:4873"
        }
    ]
```

And my npm repo:
![image](https://user-images.githubusercontent.com/1401809/80815550-78098580-8c00-11ea-87bb-2eda8e7dea0d.png)

I have Verdaccio 4.6.2.

... And finally in VS Code:
![image](https://user-images.githubusercontent.com/1401809/80815649-a6876080-8c00-11ea-90cb-cfcfcb1d5f15.png)

What am I missing?

Thanks

**Comment by jfthuong** [comment]
FYI: I got the following log in my Verdaccio log each time I refresh the extension to get the list of private extensions (I don't know if this is useful).
```
 http <-- 200, user: null(127.0.0.1), req: 'GET /-/v1/search?text=*&size=20&from=0&quality=0.65&popularity=0.98&maintenance=0.5', bytes: 0/63
 http <-- 200, user: null(127.0.0.1), req: 'GET /-/v1/search?text=*&size=20&from=0&quality=0.65&popularity=0.98&maintenance=0.5', bytes: 0/63
```

**Comment by joelspadin-garmin** [comment]
Those logs mean Verdaccio is getting the requests, so that is good. The first things I'd check are:

First, check if Verdaccio responds with any packages when given the query you logged. You should be able to open `localhost:4873/-/v1/search?text=*&size=20&from=0&quality=0.65&popularity=0.98&maintenance=0.5` in a web browser and see some JSON data about your packages. If not, Verdaccio may not accept `"*"` as a search term. Try changing the `text` parameter in that URL to different things until you find something that works. Then add it as a `query` option to your Private Extension Manager registry config. 

If it is responding with packages, check the output panel (Ctrl+Shift+U) and see if "Private Extension Manager" appears in the dropdown. If Private Extension Manager is discarding packages for any reason other than not having "engines.vscode" in the package.json, it should log a message here.

Also, do you have Verdaccio set up to mirror the entire NPM registry or just hold your packages? If the former, Private Extension Manager is going to try to search through _every_ package in the registry, which probably isn't going to work. I believe you can disable mirroring by removing the uplinks from your [config file](https://verdaccio.org/docs/en/configuration.html#uplinks). If you need the registry to hold more than just extensions for some reason, you can put some unique keyword on all your extensions and add a query to the Private Extension Manager config.

**Comment by jfthuong** [comment]
> Verdaccio may not accept "*" as a search term

Indeed, that was the issue: entering a keyword did the trick.

Do you think it could be interesting to add a note somewhere in the README to warn users that they might have to put a `query` for some NPM package distribution (e.g. Verdaccio)?

**Comment by joelspadin-garmin** [comment]
> Do you think it could be interesting to add a note somewhere in the README to warn users that they might have to put a query for some NPM package distribution (e.g. Verdaccio)?

Yep. Will do.

**Comment by kizivat** [comment]
I wonder how did @jfthuong manage to make your extension work with Verdaccio? Mine responds with `404` on the `/-/v1/search` endpoint. The Verdaccio's frontend queries `/-/verdaccio/search/{queryString}` instead.

**Comment by jfthuong** [comment]
@kizivat 

It has been a while and I did not use Verdaccio very long (migrated to JFrog Artifactory repository).

From what I remember, you just need to have some keywords in your extensions and add the keyword in a `query` option.

For example, *settings.json* from VS Code might look like:

```json
"privateExtensions.registries": [
        {
            "name": "Registry for Kizivat Extensions",
            "registry":  "https://myrepo.com/npm/kizivat-extensions/",
            "enablePagination": false,
            "query": "kizivat"
        }
    ],
```

And in the *package.json* of your extension, you have something like:
```json
    "keywords": [
        "theme",
        "color",
        "icons",
        "kizivat"
    ],
```

**Comment by kizivat** [comment]
@jfthuong Thanks for the response. I found out that my version of Verdaccio didn't support up to date NPM registry API (`/-/v1/search` endpoint).

I needed to update Verdaccio, but then I also had problem with Verdaccio running on localhost.

At last I needed to set Verdaccio `listen` setting to use my local IP instead of `localhost` and use the IP in the extension settings as well.
