### ISSUE TITLE
Why not replace Sonatype Nexus or Verdaccio by OpenVSX

### ISSUE THREAD

**Issue by yuzhidi** [joelspadin-garmin/vscode-private-extension-manager#24]
Hi,
    Maybe using  [openvsx ](https://github.com/eclipse/openvsx) to replace Sonatype Nexus or Verdaccio is better.
    Do you have any plan？

**Comment by joelspadin-garmin** [comment]
At the moment I don't have any plans because using an NPM registry server is working well enough for us, so I can't justify spending the time to support another API.

I'm hoping the existence of openvsx helps push https://github.com/Microsoft/vscode/issues/21839 along, as I'd love to not need this extension to begin with.
