### ISSUE TITLE
Not working with JFrog Artifactory

### ISSUE THREAD

**Issue by matspi** [joelspadin-garmin/vscode-private-extension-manager#50]
A customer is using JFrog Artifactory.
We have created an NPM repo there and can publish extensions to it.
However the private-extension-manager cannot download the extensions. It gives the message

TypeError: In package "...": Expected string at time.unpublished but got null

Indeed in the response from Artifactory looks like:

`...
"time" : {
    "unpublished": null,
    "0.0.1": "2021-07-01T12:12:12.123Z",
... 
`

We did not find any way to have Artifactory enter a date there or omit the _unpublished_ line.

The only way I found to get rid of this issue is to modify the private-extension-manager by relaxing the type checking in Registry.ts.

What else can we do?

**Comment by smuel1414** [comment]
@matspi 
I'm using it with JFrog Artifactory and it's working fine I managed to download.
Maybe you need to pack the extension differently.

**Comment by matspi** [comment]
@smuel1414 Thanks for the comment.
Actually, when we manually go to artifactory and edit the `package.json` and remove the `"unpublished": null` line, it is working flawlessly.

But this line is added again by artifactory upon the next publish.

We have no idea why this line is added.

Could you do me a favor and check the `package.json` created in your Artifactory?
It is the file at `<repo>/.npm/<package_name>/package.json`.
What to you see in the `time` record at the very bottom? Are there only the versions you have uploaded together with the timestamp or does it also contain _artificial_ verisions line `unpublished`, `created` and `modified?

Any idea what could be wrong with my extension?

**Comment by smuel1414** [comment]
@matspi I will try to check on Sunday what's your artifactory version I will check this also.

**Comment by matspi** [comment]
Thank you very much @smuel1414 
It is version 
> 7.19.4 rev 71904900

**Comment by smuel1414** [comment]
> Thank you very much @smuel1414
> It is version
> 
> > 7.19.4 rev 71904900

I tested it with artifactory 6.2 ...
And didn't see any changes in package.json from what I put in it.

**Comment by nitisharora007** [comment]
Not wokring with Artifactory version 7.17.11, 

Steps followed
Step 1) Created the npm repository in artifactory.
Step 2) Installed npm and vsce package also. `npm install vsce -g`
Step 2) Point the location to npm repository and pushed a npm package after downloading it VSIX file and created the package.json using npm init. Made some changes in package.json also.
Step 3) Tested with curl to get the objects/packages of npm and it is returning successfully the packages that are published.

**Attachments**:
For every json file, uploaded with extension .txt (due to security concerns)
remote-package.txt => remote-package.json and also removed the unpublished property as stated above.
package.txt => package.json
[package.txt](https://github.com/joelspadin-garmin/vscode-private-extension-manager/files/6886628/package.txt)
[remote-package.txt](https://github.com/joelspadin-garmin/vscode-private-extension-manager/files/6886606/remote-package.txt)

Also, unable to find the "Private extension manager" from the output dropdown.
![git_issue_publish](https://user-images.githubusercontent.com/16224460/127179347-60ab58e7-93cd-44aa-9f69-034a507644bf.JPG)

Let me know, if i am doing anything wrong or missed out? Please go through it and let me know if anything else needs to be added from my side.

**Comment by joelspadin-garmin** [comment]
> The only way I found to get rid of this issue is to modify the private-extension-manager by relaxing the type checking in Registry.ts.

It is odd that your registry is returning `null` for a timestamp instead of just leaving that field out, but `getVersionTimestamp()` should correctly handle a null/undefined entry in `package.time`, so I think it would be fine to change `PackageVersionData` to allow `time` to be a record of string or null.

**Comment by nitisharora007** [comment]
> Not working with Artifactory version 7.17.11,
> 
> Steps followed:
> Step 1) Created the npm repository in artifactory.
> Step 2) Installed npm and vsce package also. `npm install vsce -g`
> Step 2) Point the location to npm repository and pushed a npm package after downloading it VSIX file and created the package.json using npm init. Made some changes in package.json also.
> Step 3) Tested with curl to get the objects/packages of npm and it is returning successfully the packages that are published.
> 
> **Attachments**:
> For every json file, uploaded with extension .txt (due to security concerns)
> remote-package.txt => remote-package.json and also removed the unpublished property as stated above.
> package.txt => package.json
> [package.txt](https://github.com/joelspadin-garmin/vscode-private-extension-manager/files/6886628/package.txt)
> [remote-package.txt](https://github.com/joelspadin-garmin/vscode-private-extension-manager/files/6886606/remote-package.txt)
> 
> Also, unable to find the "Private extension manager" from the output dropdown.
> ![git_issue_publish](https://user-images.githubusercontent.com/16224460/127179347-60ab58e7-93cd-44aa-9f69-034a507644bf.JPG)
> 
> Let me know, if i am doing anything wrong or missed out? Please go through it and let me know if anything else needs to be added from my side.

@matspi and @smuel1414 can you please look into the issue. 
I am getting the response from the artifactory in the browser but the VS Code does not show up any extension list.
https://<artifactory_url>/artifactory/api/npm/npm-vscode-ext-test/-/v1/search?text=*&size=20&from=0&quality=0.65&popularity=0.98&maintenance=0.5
 
 Note: I modified the package.json to have dummy name in the author, will that be causing the issue?

**Comment by smuel1414** [comment]
@nitisharora007 
For me to make it work with artifactory I needed to  add `limit=20` and `enablePagination=false` in the settings.
```
"privateExtensions.registries": [
    {
        "name": "extentions",
        "registry": "https://host:port/path",
        "enablePagination": false,
        "limit": 20
    }
]
```

**Comment by matspi** [comment]
> It is odd that your registry is returning `null` for a timestamp instead of just leaving that field out, but `getVersionTimestamp()` should correctly handle a null/undefined entry in `package.time`, so I think it would be fine to change `PackageVersionData` to allow `time` to be a record of string or null.

That is exactly what I did.

I changed the `t.string` to `t.union([t.string, t.null])`

@joelspadin-garmin Would you consider accepting a pull request with those changes and integrate it into the next release?

**Comment by joelspadin-garmin** [comment]
> Would you consider accepting a pull request with those changes and integrate it into the next release?

Gladly!

**Comment by heyongwei** [comment]
This is my first time to use JFrog Artifactory ,I don`t know why i get the 404 response where i call the ..../-/v1/search?text=*&.. . Am i choosed a wrong repository or miss some config？ the url  /-/v1/search is a standard resf api for npm register service?
