### ISSUE TITLE
No indication of extension being installed already, neither update notification visible for vsix files downloaded from marketplace

### ISSUE THREAD

**Issue by MarekLani** [joelspadin-garmin/vscode-private-extension-manager#52]
Hello, first of all thank you for your work on this extension!

In my scenario I am trying to create list of allowed extensions and push it thru private extension manager, in other words download several internally approved vsix files of official marketplace published extensions and distributed them from my private npm repo, but I see some issues with the extension described below.

As an example I downloaded [typescript extension vsix file](https://marketplace.visualstudio.com/items?itemName=ms-vscode.vscode-typescript-next) and created simple npm package and pushed it to my verdaccio repository. It is visible in private extension manager view, when I click install, it gets installed, I get prompted to reload window to take effect, but afterwards there is no indication in private extension manager, that it was indeed installed. When I navigate to marketplace tab, I see it was installed successfully.  Also as the private extension manager does not capture that the extension was already installed, I believe it also does not keep track of available updates.

Please is the over described scenario with downloaded vsix files of official marketplace extensions supported?

In case it was needed I am attaching my package.json file:

```
{
    "name": "vscode-typescript-next",
    "version": "4.4.20210727",
    "description": "lorem",
    "license": "ISC",
    "author": {
        "name": "Random",
        "email": "email@email.com"
    },
    "publisher": " Microsoft",
    "engines": {
        "vscode": "^1.40.0"
    },
    "files": [
        "typescript-next-4.4.20210727.vsix"
    ],
    "publishConfig": {
        "registry": "http://localhost:4873"
    },
    "scripts": {
    }
}
```

**Comment by joelspadin-garmin** [comment]
That was not an intended use case, but I think it should work. I think the reason it does not appear is because the official marketplace translates publisher names (Microsoft) into tags (ms-vscode, etc,), while Private Extension Manager does not. If you change the publisher in that package to "ms-vscode", then Private Extension Manager should see the installed extension as matching the private package.

You should also be aware that if a package is in the official marketplace as well as your private registry, VS Code will still auto update extensions from the official marketplace. If you do not have access to the official marketplace, then https://github.com/eclipse/openvsx/wiki/Using-Open-VSX-in-VS-Code might also do what you want (and probably better).

**Comment by MarekLani** [comment]
@joelspadin-garmin  thank you very much for such quick response and advice. I confirm your suggested fix worked. Also thank you for suggesting the openvsx, I will review to see if it is better fit.
