### ISSUE TITLE
Make the extension available to ALL projects

### ISSUE THREAD

**Issue by Stephanevg** [joelspadin-garmin/vscode-private-extension-manager#94]
Hi again,

Currently, the this extension seems to work only a per project way. Is there a way to use it globally on a system ?

I would like to use the same extension across all my projects on a specific system. How could I make the **private extensions** available globally ?

>note: The extension that gets installed using the **the private extension manager** is available throughout the different projects. It looks like we can only **manage** the extension from that one project where we installed it from. Currently, you can manage the extension `only` from where you have configured the registry (where the `private.extension.json` is located).

**Comment by joelspadin-garmin** [comment]
I'm not sure I understand what you're asking for. You can configure the extension registries globally with the `privateExtensions.registries` setting, which will make the same extensions available for installation everywhere. You can only configure the extension _recommendations_ per project (because that is just an indications of which extensions are useful for that project), but extensions are installed globally.

**Comment by Stephanevg** [comment]
Hi, yes you are right. Somehow, I missed that part when I read the documentation.
